[package]
name = "cactus-com"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
anyhow = "1.0.102"
regex = "1.12.3"
cactus-foundation = { path = "../cactus-foundation" }
strum = "0.28.0"
strum_macros = "0.28.0"
enum_dispatch = "0.3"
chrono = "0.4.44"
uuid = { version = "1.21.0", features = ["v4"] }
log = "0.4.28"